/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import clases.ConexionDB;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComponent;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class PantallaConsulta extends javax.swing.JInternalFrame {

    /**
     * Creates new form PantallaConsulta
     */
    public PantallaConsulta() {
        initComponents();
        this.ocultarBarraTitulo();
    }

    public void ocultarBarraTitulo() {
        Barra = ((javax.swing.plaf.basic.BasicInternalFrameUI) getUI()).getNorthPane();
        dimBarra = Barra.getPreferredSize();
        Barra.setSize(0, 0);
        Barra.setPreferredSize(new Dimension(0, 0));
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtISBN = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tcons = new javax.swing.JTable();
        jConsulta = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jleditorial = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jlautor = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jlrecurso = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setNormalBounds(new java.awt.Rectangle(150, 50, 0, 0));

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jLabel1.setText("ISBN");

        jtISBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtISBNActionPerformed(evt);
            }
        });
        jtISBN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtISBNKeyTyped(evt);
            }
        });

        tcons.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tcons.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        tcons.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tcons.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tconsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tcons);

        jConsulta.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cons.jpg"))); // NOI18N
        jConsulta.setText("Consultar");
        jConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConsultaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jLabel2.setText("NOMBRE");

        jleditorial.setText("#");

        jLabel3.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jLabel3.setText("ESTADO");

        jlautor.setText("#");

        jLabel4.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jLabel4.setText("IDIOMA");

        jlrecurso.setText("#");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 871, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(jConsulta)
                        .addGap(0, 530, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel2)
                .addGap(48, 48, 48)
                .addComponent(jleditorial, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jlautor, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlrecurso, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jConsulta))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jleditorial, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jlautor, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jlrecurso))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        setBounds(0, 0, 931, 354);
    }// </editor-fold>//GEN-END:initComponents

    private void jConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConsultaActionPerformed
        // TODO add your handling code here:
        String ISBN = jtISBN.getText();
        String[] dato = new String[3];
       
        try {
            ConexionDB coneccion = new ConexionDB(); //Creamos un objeto de la clase Coneccion DB
            Connection con = coneccion.obtenerConexion();
            String cons = "SELECT NOMBRE_REC, ESTADO, IDIOMA FROM RECURSOS_BIBLIOGRAFICOS "
                    + "WHERE ISBN LIKE'" + ISBN + "'"; // Manipulacion de tablas
            ResultSet consulta = coneccion.consulta(cons);
            consulta.next();
            jleditorial.setText(consulta.getString(1));
            jlautor.setText(consulta.getString(2));
            jlrecurso.setText(consulta.getString(3));
        } catch (Exception ex) {
            System.out.print(ex.getMessage());

        }
     mostrardatos(jtISBN.getText()); 

    }//GEN-LAST:event_jConsultaActionPerformed
  void mostrardatos(String valor) {
        // Metodo para consultar en la BD
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("TITULO");
        modelo.addColumn("DESCRIPCION");
        modelo.addColumn("PAGINAS");
        modelo.addColumn("EDICION");
        modelo.addColumn("ESTADO");
        modelo.addColumn("IDIOMA");
        
        tcons.setModel(modelo);
        String sql = "SELECT * FROM RECURSOS_BIBLIOGRAFICOS, RECURSO_DETALLE WHERE RECURSO_DETALLE.ISBN = RECURSOS_BIBLIOGRAFICOS.ISBN";
        

        String[] datos = new String[10];
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                datos[0] = rs.getString(9);
                datos[1] = rs.getString(10);
                datos[2] = rs.getString(11);
                datos[3] = rs.getString(12);
                datos[4] = rs.getString(5);
                datos[5] = rs.getString(6);         
                modelo.addRow(datos);
            }
            tcons.setModel(modelo);
        } catch (SQLException ex) {
            Logger.getLogger(PantallaBibliotecario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void tconsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tconsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tconsMouseClicked

    private void jtISBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtISBNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtISBNActionPerformed

    private void jtISBNKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtISBNKeyTyped


    }//GEN-LAST:event_jtISBNKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jConsulta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlautor;
    private javax.swing.JLabel jleditorial;
    private javax.swing.JLabel jlrecurso;
    private javax.swing.JTextField jtISBN;
    private javax.swing.JTable tcons;
    // End of variables declaration//GEN-END:variables
    private JComponent Barra = ((javax.swing.plaf.basic.BasicInternalFrameUI) getUI()).getNorthPane();
    private Dimension dimBarra = null;
    ConexionDB cc = new ConexionDB();
    Connection cn = cc.obtenerConexion();
}
